apiVersion: v1
kind: Service
metadata:
  name: tgdex-monolith-svc
spec:
  selector:
    app.kubernetes.io/name: tgdex-monolith
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
