import enum


class DiscussionsTypeEnum(enum.Enum):
    PUBLIC = "PUBLIC"
    GENERAL = "GENERAL"
    GETTING_STARTED = "GETTING_STARTED"
    PRODUCT_FEEDBACK = "PRODUCT_FEEDBACK"
    PRODUCT_ANNOUNCEMENTS = "PRODUCT_ANNOUNCEMENTS"


class DiscussionsCategoryEnum(enum.Enum):
    DATA_BANKS = "DATA_BANKS"
    AI_MODELS = "AI_MODELS"
    USECASES = "USECASES"
    CHALLENGES = "CHALLENGES"
    OTHERS = "OTHERS"


class DiscussionsStatusEnum(enum.Enum):
    PENDING = "PENDING"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class CommentsStatusEnum(enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    HIDDEN = "HIDDEN"

class CommentReportStatusEnum(str, enum.Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    IGNORED = "IGNORED"

class CommentReportReasonEnum(str, enum.Enum):
    DISALLOWED_AI_CONTENT = "DISALLOWED_AI_CONTENT"
    UNRELATED_CONTENT = "UNRELATED_CONTENT"
    HIGH_VOLUME_SPAM = "HIGH_VOLUME_SPAM"

    OFFENSIVE = "OFFENSIVE"
    NSFW = "NSFW"
    UNPROFESSIONAL = "UNPROFESSIONAL"

    JOB_POSTING = "JOB_POSTING"
    LOW_VALUE = "LOW_VALUE"
    WRONG_TOPIC = "WRONG_TOPIC"

    SIMILAR_CONTENT = "SIMILAR_CONTENT"
    PLAGIARISM = "PLAGIARISM"

    SELF_PROMOTION = "SELF_PROMOTION"
    VOTE_MANIPULATION = "VOTE_MANIPULATION"

    OTHER = "OTHER"